# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mK9-wBLO9O3RMPUpt_fpG0iRXTZwKrQC
"""

import time
import numpy as np

def fibo(n:int, cofre = {}):
    if n < 0 :
      return "Insira somente numeros positivos!"

    elif n <= 1:
      return n

    else:
      cofre[n] = fibo(n-1, cofre) + fibo(n-2, cofre)
      return cofre[n]

n = int(input("Insira um numero: "))


for z in range(3):
  lista = []
  for i in range(n+1):
    start = time.time_ns()
    resultado = fibo(i)
    end = time.time_ns()
    tempo_total = end - start
    media = np.mean(tempo_total)
    desvio = np.std(tempo_total)


    print(f'Tempo de execução: {tempo_total}\nValor inserido: {n}\nResultado: {resultado}')